services:
  - type: web
    name: php-backend
    env: php
    buildCommand: composer install
    startCommand: php -S 0.0.0.0:10000
    plan: free
    branch: main
    rootDir: .
    envVars:
      - key: PHP_VERSION
        value: 8.1
